version: "3.9"
services:
  postgres:
    build:
      context: .
    environment:
      POSTGRES_DB: "stackoverkata_jm"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql